version: "2"

services:
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=pugiemonn
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/dev/etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./laravel/public:/var/www/laravel/public
    ports:
      - 80:80
      - 443:443
    links:
      - phpfpm
    depends_on:
      - phpfpm
  phpfpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=pugiemonn
      - DB_USERNAME=root
      - DB_PASSWORD=pass
  composer:
    image: composer:latest
    volumes:
      - ./laravel:/var/www/laravel
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env
    command: install
