# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  # twitter_api_key: ''
  # twitter_api_secret: ''
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>

development:
  secret_key_base: d5b6fe080628c8290da2bf1029b3113342e5689f2c541a8ae5fc573d46fe27f88ab7b462fa3774bfb565cd7e8bdb945f9d3ce2fba25f813dc0f258a49582e0df
  <<: *default_twitter
  # secret_key_base: 29ae8786307ccd379b1b347bd8e98a41e7bf2c196840e6e04ae43448480662b9314b3139b02aca1d06975844e61072b41e2e9f9d28ea5e33e6277ef71a3443bc

test:
  secret_key_base: 0221a48fc052f9a9aa04f890abab08b2d649fd9a6a6447fc7abb110293204a8a2de055e7710d1cda7cf9ed1fd3fc96bd5fa1c0f95acea27a96b31127cd92fbfd
  <<: *default_twitter
  # secret_key_base: 634325d42ead99df985a1843778d6d8450347221ff317c684eaa44e41f8a744188a24937d13c2cace0d167688e7b02e466848a08ce66d468eb4481575b2da0cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
